### ISSUE TITLE
red circle outline incorectly sized 

### ISSUE THREAD

**Issue by om3ga6400** [dngaa/dngaa.github.io#16]
![{EAFA27BE-5052-4186-A5AA-E3B0610865B1}](https://github.com/user-attachments/assets/065470be-25ee-4842-ba07-7f540b7f3704)
it is not centered somthing so one side is bigger

**Comment by dngaa** [comment]
that's really weird, it looks fine for me 
![Screenshot 2024-11-21 194939](https://github.com/user-attachments/assets/819a612a-f3b2-442b-ad6b-91b55f861191)

**Comment by om3ga6400** [comment]
@dngaa found the issue you it looks perfect on 110% zoom

**Comment by om3ga6400** [comment]
![{216A0F9E-2C95-4153-8B5E-32C584F195D6}](https://github.com/user-attachments/assets/05b85e98-8f2d-408b-a0dc-e3970ba46d51)
110
![{6ED138F9-0A02-4A2E-BF5D-18392E9B1D8E}](https://github.com/user-attachments/assets/23ed7bd2-7309-4462-9723-3cbfc5bb1272)
100

**Comment by dngaa** [comment]
I've been trying to figure out what the issue is but i have no idea tbh.
