### ISSUE TITLE
[removed]

### ISSUE THREAD

**Issue by ninjaguardian** [dngaa/dngaa.github.io#4]
[removed]

**Comment by Githubuser10103** [comment]
i found u gimme local storage

**Comment by ninjaguardian** [comment]
So I did some testing and figured out that your cookies store a GUID. Ergo probably letting you change your save data but it is over written. Then again, this probably not related to the bug. I played through the game. Saved once at Brock's gym and then at cerulean and afk'ed for the night. In the morning, I went on safari and the page reloaded. I was back at Brock's gym, not cerulean. This is possibly due to the way that safari, and possibly IOS/IpadOS handle data. Or I'm just wrong. Not the best at coding.
